mobilejazz/harmony-kotlin

core/src/main/java/com/mobilejazz/harmony/kotlin/core/repository/validator/vastra/strategies/timestamp/TimestampValidationStrategy.kt, core/src/test/java/com/mobilejazz/harmony/kotlin/core/repository/validator/TimestampValidationStrategyDataSourceTest.kt, core/src/test/java/com/mobilejazz/harmony/kotlin/core/repository/validator/vastra/strategies/timestamp/TimestampValidationStrategyTest.kt, sample/src/main/java/com/mobilejazz/sample/core/data/model/ItemEntity.kt, sample/src/main/java/com/mobilejazz/sample/core/data/network/ItemNetworkDataSource.kt, sample/src/main/java/com/mobilejazz/sample/di/general/ItemDI.kt, sample/src/main/java/com/mobilejazz/sample/di/general/ItemIdsDI.kt
- Fix red tests /core/repository/validator/TimestampValidationStrategyDataSourceTest.kt
- Move @transient annotation to the parent class so Gson can recognise the attribute in child classes 
- Fix unused copy object
- Update DI with the new SerializationDataSourceMapper
=> Update Harmony's sample

common/src/commonMain/kotlin/com.harmony.kotlin/data/datasource/network/GenericNetworkDataSource.kt
Fix problem with is not an integer or/and is not a string
=> Fixed Check datasource id, now if is not a int and is not a string

android/build.gradle, android/src/main/java/com/mobilejazz/harmony/kotlin/android/di/AppInjector.kt, android/src/main/java/com/mobilejazz/harmony/kotlin/android/ext/AndroidExt.kt, android/src/main/java/com/mobilejazz/harmony/kotlin/android/ext/Delegates.kt, android/src/main/java/com/mobilejazz/harmony/kotlin/android/repository/validator/vastra/strategies/reachability/ReachabilityValidationStrategy.kt, android/src/main/java/com/mobilejazz/harmony/kotlin/android/threading/Executors.kt, build.gradle, buildsystem/dependencies.gradle, gradle/wrapper/gradle-wrapper.properties
[**CAN BE MERGED**]
This is a Harmony Kotlin Android PR to update dependencies (prior to adding support for ViewBinding)
=> Update gradle, kotlin, target sdk & dependencies version

android/build.gradle, android/src/main/java/com/mobilejazz/harmony/kotlin/android/ui/base/BaseActivity.kt, android/src/main/java/com/mobilejazz/harmony/kotlin/android/ui/base/BaseFragment.kt
[**CAN BE MERGED**]
This is a Harmony Kotlin Android PR that adds support to base Activity/Fragment for ViewBinding
=> Add ViewBinding support to base Activity/Fragment

common/src/commonMain/kotlin/com.harmony.kotlin/common/exceptions/TryCatchHelpers.kt
- If the block executed throws an exception it will be catched and a default value will be returned
=> Add tryOrDefault helper method.

harmony-kotlin/build.gradle, harmony-kotlin/src/androidMain/kotlin/com/harmony/kotlin/common/Coroutines.kt, harmony-kotlin/src/commonMain/kotlin/com.harmony.kotlin/common/Coroutines.kt, harmony-kotlin/src/commonTest/kotlin/com/harmony/kotlin/data/datasource/memory/InMemoryDataSourceTests.kt, harmony-kotlin/src/iosMain/kotlin/com/harmony/kotlin/common/Coroutines.kt, harmony-kotlin/src/jvmMain/kotlin/com/harmony/kotlin/common/Coroutines.kt
Added unit tests to the InMemoryDataSource class
=> InMemoryDataSource Tests

harmony-kotlin/src/androidMain/kotlin/com/harmony/kotlin/common/logger/BugfenderLogger.kt
- Previously only the Throwable message was logged
=> Improve BugfenderLogger to log the complete stackTrace of a Throwable

CHANGELOG.md, README.md, buildSrc/src/main/groovy/gradle-mvn-push.gradle, buildSrc/src/main/java/Dependencies.kt
This PR applies changes needed to create a new release
=> Release 4.0

harmony-kotlin/src/commonMain/kotlin/com.harmony.kotlin/common/logger/VoidLogger.kt
* Asana task link: https://app.asana.com/0/0/1202482193184068/f
=> KMM-4068 :: Feature internal :: Create void logger

harmony-kotlin/src/commonMain/kotlin/com.harmony.kotlin/data/datasource/RetryDataSource.kt, harmony-kotlin/src/commonTest/kotlin/com/harmony/kotlin/data/datasource/RetryDataSourceTest.kt
* Asana task link: https://app.asana.com/0/0/1202482282227926/f
=> KMM-7926 :: Feature internal :: Create retry data source

buildSrc/src/main/java/Dependencies.kt, gradle.properties, harmony-kotlin/build.gradle.kts, harmony-kotlin/src/commonMain/kotlin/com.harmony.kotlin/common/logger/KtorHarmonyLogger.kt, harmony-kotlin/src/commonMain/kotlin/com.harmony.kotlin/data/datasource/memory/InMemoryDataSource.kt, harmony-kotlin/src/commonMain/kotlin/com.harmony.kotlin/data/datasource/network/NetworkQueryToKtorExtensions.kt, harmony-kotlin/src/commonMain/kotlin/com.harmony.kotlin/data/datasource/network/ktor/KtorConfig.kt, harmony-kotlin/src/commonMain/kotlin/com.harmony.kotlin/library/oauth/OAuthProvider.kt, harmony-kotlin/src/commonMain/kotlin/com.harmony.kotlin/library/oauth/data/datasource/network/OAuthNetworkDataSource.kt, harmony-kotlin/src/commonTest/kotlin/com/harmony/kotlin/data/datasource/network/ApiMock.kt, harmony-kotlin/src/commonTest/kotlin/com/harmony/kotlin/data/datasource/network/GetNetworkDataSourceTests.kt, harmony-kotlin/src/commonTest/kotlin/com/harmony/kotlin/data/mapper/CBORObjectToByteArrayMapperTests.kt, sample-android-compose/build.gradle.kts, sample-core/src/commonMain/kotlin/com/mobilejazz/kmmsample/core/NetworkProvider.kt, sample-core/src/commonMain/kotlin/com/mobilejazz/kmmsample/core/feature/hackerposts/domain/interactor/GetHackerNewsPostInteractor.kt
This PR updates dependencies, the most important updates are:
- Kotlin to 1.7.10
- Ktor to 2.0.3 
**IMPORTANT**
- After this PR is merged the new native memory management model must be enabled in the projects: https://github.com/JetBrains/kotlin/blob/master/kotlin-native/NEW_MM.md#switch-to-the-new-mm
Note that this PR goes to **feature/mvi** instead of master
* Asana task link: https://app.asana.com/0/1109863238977521/1202789494669763
=> KMM-9763 :: Feature :: Update dependencies

CHANGELOG.md, README.md, buildSrc/src/main/groovy/gradle-mvn-push.gradle
Note that this PR goes to feature/update_dependencies instead of master
Merge / Pull request information:
Asana task link: https://app.asana.com/0/1109863238977521/1202789494669766
=> KMM-9766 :: Feature :: Release 5.0

README.md, sample-core/src/commonMain/kotlin/com/mobilejazz/kmmsample/core/feature/hackerposts/HackerNewsPostsProvider.kt, sample-core/src/commonMain/kotlin/com/mobilejazz/kmmsample/core/feature/hackerposts/domain/interactor/GetHackerNewsPostInteractor.kt, sample-core/src/commonMain/kotlin/com/mobilejazz/kmmsample/core/feature/hackerposts/domain/interactor/GetHackerNewsPostsInteractor.kt
This PR includes:
- Fix the README.md with correct dependencies (5.0)
- Fix sample Interactors to make use of a CorotutineContext.
* Asana task link: https://app.asana.com/0/1109863238977521/1202890422934066/f
=> KMM-4066 :: Feature :: Minor fixes

harmony-kotlin/src/commonTest/kotlin/com/harmony/kotlin/data/datasource/network/DeleteNetworkDataSourceTest.kt, harmony-kotlin/src/commonTest/kotlin/com/harmony/kotlin/data/datasource/network/GetNetworkDataSourceTests.kt, harmony-kotlin/src/commonTest/kotlin/com/harmony/kotlin/data/datasource/network/PutNetworkDataSourceTest.kt
* Asana task link: https://app.asana.com/0/1109863238977521/1202713346925022
* Based on https://github.com/mobilejazz/harmony-kotlin/issues/76
=> KMM-5022 :: Feature Internal :: Add unit tests for PutNetworkDataSource & DeleteNetworkDataSource

harmony-kotlin/src/commonMain/kotlin/com.harmony.kotlin/common/logger/Logger.kt
* Asana task link: https://app.asana.com/0/1109863238977521/1202928756785654
=> KMM-5654 :: Feature :: Remove unused vararg from logger interface

harmony-kotlin/src/iosMain/kotlin/com/harmony/kotlin/common/logger/IOSConsoleLogger.kt
* Asana task link: https://app.asana.com/0/1109863238977521/1202971884260988/f
=> KMM-0988 :: Create IOSConsoleLogger class within the ios folder using Logger interface

.github/workflows/build.yml
* Asana task link: https://app.asana.com/0/1109863238977521/1202971884261024
=> KMM-1024 :: Update the build phase in Github workflow to execute klint and detekt

git-hooks.gradle.kts, harmony-kotlin/build.gradle.kts, scripts/git-hooks/pre-commit.sh
* Asana task link: https://app.asana.com/0/1109863238977521/1202971884261020/f
=> KMM-1020 :: Feature :: Config pre-commit hooks in harmony-kotlin

.github/workflows/build.yml, build.gradle.kts, gradle/libs.versions.toml
* Asana task link: https://app.asana.com/0/1109863238977521/1203027755108455/f
=> KMM-8455 :: Feature Internal :: Split CI pipelines job between macos agent and ubuntu agent

.github/workflows/build.yml, build.gradle.kts
Sample of a test report: https://github.com/mobilejazz/harmony-kotlin/actions/runs/3144769439/jobs/5111259781
Detekt reports have been also included when detekt fails. Sample of a detekt report: https://github.com/mobilejazz/harmony-kotlin/actions/runs/3131481368/jobs/5082886060
* Asana task link: https://app.asana.com/0/1109863238977521/1203054651611484/f
=> KMM-1484 :: Feature :: Add unit tests report in github actions

build.gradle.kts, gradle/libs.versions.toml
* Asana task link: https://app.asana.com/0/409913176844723/1203078456546794
=> KMM-5791 :: Feature :: Upgrade libraries/dependencies

.github/CODEOWNERS
* Asana task link: https://app.asana.com/0/409913176844723/1203174847585981
- Added to CODEOWNERS people who showed interest and have knowledge about kotlin
=> DOC-5981 :: Feature Internal :: Harmony Owners

gradle/libs.versions.toml
* Asana task link: https://app.asana.com/0/1109863238977521/1203446595616794
- Upgrade dependencies
=> KMM-6794 :: Feature :: Upgrade libraries/dependencies

gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, harmony-kotlin/build.gradle.kts, settings.gradle
* Asana task link: https://app.asana.com/0/409913176844723/1203721748485504
=> KMM-5504 :: Feature :: Upgrade libraries/dependencies

CHANGELOG.md, README.md, buildSrc/src/main/groovy/gradle-mvn-push.gradle
* Asana task link: https://app.asana.com/0/409913176844723/1203843385050152
=> KMM-0152 :: Feature :: Release 6.0.0
